"""
Safe execution environment for LLM-generated CadQuery code.

This module provides sandboxed execution of Python code generated by LLMs,
with security constraints to prevent malicious or unsafe operations.
"""

import ast
import re
import logging
from typing import Any, Optional
import cadquery as cq

from ..schemas import CadQueryCodeDesign

logger = logging.getLogger(__name__)


# =============================================================================
# Security Configuration
# =============================================================================

# Forbidden keywords/patterns that indicate unsafe operations
FORBIDDEN_PATTERNS = [
    r'\bopen\s*\(',                # File I/O
    r'\bexec\s*\(',                # Code execution
    r'\beval\s*\(',                # Expression evaluation
    r'\b__import__\s*\(',          # Dynamic imports
    r'\bcompile\s*\(',             # Code compilation
    r'\bsubprocess\b',             # Process spawning
    r'\bos\.',                     # OS operations
    r'\bsys\.',                    # System operations
    r'\bshutil\.',                 # File operations
    r'\bpickle\.',                 # Serialization (can execute code)
    r'\b__builtins__\b',           # Access to builtins
    r'\b__globals__\b',            # Access to globals
    r'\b__locals__\b',             # Access to locals
    r'\bwhile\s+True\s*:',         # Infinite loops
    r'\bfor\s+\w+\s+in\s+range\s*\(\s*\d{7,}', # Very large loops
]

# Maximum code length (characters)
MAX_CODE_LENGTH = 10000

# Maximum number of lines
MAX_LINES = 200

# Allowed imports (whitelist)
ALLOWED_IMPORTS = {
    'cadquery',
    'cq',
    'math',
}


# =============================================================================
# Validation Functions
# =============================================================================

def validate_syntax(code: str) -> tuple[bool, Optional[str]]:
    """
    Validate Python syntax without executing.
    
    Args:
        code: Python code string
        
    Returns:
        (is_valid, error_message)
    """
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax error at line {e.lineno}: {e.msg}"


def check_forbidden_patterns(code: str) -> tuple[bool, Optional[str]]:
    """
    Check for forbidden operations using regex patterns.
    
    Args:
        code: Python code string
        
    Returns:
        (is_safe, violation_message)
    """
    for pattern in FORBIDDEN_PATTERNS:
        match = re.search(pattern, code, re.MULTILINE | re.IGNORECASE)
        if match:
            return False, f"Forbidden operation detected: {match.group()}"
    return True, None


def check_imports(code: str) -> tuple[bool, Optional[str]]:
    """
    Validate that only allowed imports are used.
    
    Args:
        code: Python code string
        
    Returns:
        (is_valid, error_message)
    """
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return False, "Cannot parse code for import validation"
    
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                module = alias.name.split('.')[0]
                if module not in ALLOWED_IMPORTS:
                    return False, f"Import not allowed: {alias.name}"
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                module = node.module.split('.')[0]
                if module not in ALLOWED_IMPORTS:
                    return False, f"Import not allowed: from {node.module}"
    
    return True, None


def validate_code_length(code: str) -> tuple[bool, Optional[str]]:
    """
    Check code length constraints.
    
    Args:
        code: Python code string
        
    Returns:
        (is_valid, error_message)
    """
    if len(code) > MAX_CODE_LENGTH:
        return False, f"Code too long: {len(code)} chars (max {MAX_CODE_LENGTH})"
    
    lines = code.split('\n')
    if len(lines) > MAX_LINES:
        return False, f"Too many lines: {len(lines)} (max {MAX_LINES})"
    
    return True, None


# =============================================================================
# Safe Execution
# =============================================================================

def execute_cadquery_code(
    design: CadQueryCodeDesign,
    timeout: int = 30
) -> tuple[Optional[cq.Workplane], Optional[str]]:
    """
    Safely execute generated CadQuery code.
    
    This function performs multiple validation checks before executing
    the code in a restricted namespace.
    
    Args:
        design: CadQueryCodeDesign containing the code to execute
        timeout: Maximum execution time in seconds (not implemented yet)
        
    Returns:
        (workplane, error_message) - workplane is None if execution failed
    """
    code = design.code
    
    # Step 1: Length validation
    is_valid, error = validate_code_length(code)
    if not is_valid:
        logger.error(f"Code length validation failed: {error}")
        return None, error
    
    # Step 2: Syntax validation
    is_valid, error = validate_syntax(code)
    if not is_valid:
        logger.error(f"Syntax validation failed: {error}")
        return None, error
    
    # Step 3: Check forbidden patterns
    is_safe, error = check_forbidden_patterns(code)
    if not is_safe:
        logger.error(f"Security validation failed: {error}")
        return None, error
    
    # Step 4: Validate imports
    is_valid, error = check_imports(code)
    if not is_valid:
        logger.error(f"Import validation failed: {error}")
        return None, error
    
    # Step 5: Execute in restricted namespace
    try:
        # Create restricted namespace with only allowed modules
        namespace = {
            'cq': cq,
            'cadquery': cq,
            '__builtins__': {
                # Minimal builtins for math operations
                'abs': abs,
                'min': min,
                'max': max,
                'round': round,
                'range': range,
                'len': len,
                'list': list,
                'dict': dict,
                'tuple': tuple,
                'int': int,
                'float': float,
                'str': str,
                'bool': bool,
                'True': True,
                'False': False,
                'None': None,
            },
        }
        
        # Allow math module if imported
        if 'math' in design.required_imports or 'import math' in code:
            import math
            namespace['math'] = math
        
        # Strip import statements from code since we pre-inject modules
        # This avoids needing __import__ in the restricted builtins
        code_lines = code.split('\n')
        cleaned_lines = []
        for line in code_lines:
            stripped = line.strip()
            # Skip import statements (cq and cadquery are already in namespace)
            if stripped.startswith('import cadquery') or stripped.startswith('import cq') or stripped.startswith('from cadquery'):
                # Comment it out instead of removing to preserve line numbers for debugging
                cleaned_lines.append(f"# {line}  # (pre-injected)")
            else:
                cleaned_lines.append(line)
        
        cleaned_code = '\n'.join(cleaned_lines)
        
        # Execute the code
        logger.info("Executing generated CadQuery code...")
        exec(cleaned_code, namespace)
        
        # Extract result from entry point
        entry_point = design.entry_point
        if entry_point not in namespace:
            error = f"Entry point '{entry_point}' not found in code. Available: {list(namespace.keys())}"
            logger.error(error)
            return None, error
        
        result = namespace[entry_point]
        
        # Validate result type
        if not isinstance(result, cq.Workplane):
            error = f"Entry point '{entry_point}' must be a CadQuery Workplane, got {type(result).__name__}"
            logger.error(error)
            return None, error
        
        # Validate result contains geometry
        try:
            # Try to get the solid - this will fail if no geometry was created
            _ = result.val()
            logger.info("✓ Code execution successful, geometry created")
            return result, None
        except Exception as e:
            error = f"Workplane contains no geometry: {str(e)}"
            logger.error(error)
            return None, error
            
    except Exception as e:
        error = f"Runtime error during code execution: {type(e).__name__}: {str(e)}"
        logger.error(error)
        return None, error


# =============================================================================
# Utility Functions
# =============================================================================

def preview_code_safety(code: str) -> dict[str, Any]:
    """
    Preview all safety checks without executing.
    
    Useful for debugging and understanding why code might fail validation.
    
    Args:
        code: Python code string
        
    Returns:
        Dictionary with validation results
    """
    results = {}
    
    # Length check
    is_valid, msg = validate_code_length(code)
    results['length_check'] = {'passed': is_valid, 'message': msg}
    
    # Syntax check
    is_valid, msg = validate_syntax(code)
    results['syntax_check'] = {'passed': is_valid, 'message': msg}
    
    # Forbidden patterns
    is_safe, msg = check_forbidden_patterns(code)
    results['security_check'] = {'passed': is_safe, 'message': msg}
    
    # Imports
    is_valid, msg = check_imports(code)
    results['import_check'] = {'passed': is_valid, 'message': msg}
    
    # Overall
    all_passed = all(check['passed'] for check in results.values())
    results['overall'] = {'passed': all_passed}
    
    return results

